---
name: Lint
on:
  pull_request: null
  
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: lint-cpp
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # Use .clang-format config file
          checks: clang-format
          tidy-checks: '' # Use .clang-tidy config file
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
      - name: lint-failfast
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
      - name: lint-python
        uses: chartboost/ruff-action@v1