---
name: Lint
on:
  pull_request: null
  
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: lint-cpp
        uses: RafikFarhad/clang-format-github-action@v3
        with:
          style: "file"
          excludes: ""
          sources: "src/**/*.c,src/**/*.cpp,src/**/*.h,src/**/*.hpp,src/**/*.hh,src/**/*.cc"
      - name: lint-python
        uses: benny123tw/action-ruff@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.